/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.admin.info;

import java.awt.Color;
import javax.swing.ImageIcon;
import mnm.DAO.NhanVienDAO;
import mnm.helper.DialogHelper;
import mnm.model.NhanVienQuanTri;

/**
 *
 * @author Duc Tien
 */
public class InfoMain extends javax.swing.JFrame {

    private NhanVienDAO nvDAO = new NhanVienDAO();
    private String id;

    /**
     * Creates new form InfoMain
     */
    public InfoMain() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        btnEdit.setFocusable(false);
        btnPre.setFocusable(false);
        btnSave.setFocusable(false);

    }

    /**
     * Thiết lập dữ liệu cho giao diện với thông tin của một Nhân viên Quản trị
     * dựa trên ID.
     *
     * @param id ID của Nhân viên Quản trị cần hiển thị thông tin.
     */
    public void setModel(String id) {
        // Lấy thông tin Nhân viên Quản trị từ cơ sở dữ liệu
        NhanVienQuanTri qt = nvDAO.selectQT(id);

        // Kiểm tra xem 'qt' có khác null không
        if (qt != null) {
            // Hiển thị thông tin của Nhân viên Quản trị trên giao diện
            txtID.setText(qt.getId());
            txtEmail.setText(qt.getEmail());
            txtName.setText(qt.getName());
            txtSdt.setText(qt.getSdt());

            // Kiểm tra xem 'qt.getHinh()' có khác null không trước khi tạo ImageIcon
            if (qt.getHinh() != null) {
                String hinh = qt.getHinh();
                // Đặt hình ảnh cho thành phần ImageIcon từ tệp hình ảnh
                imageAvatar1.setIcon(new ImageIcon(getClass().getResource("/mnm/images/" + hinh)));
            } else {
                // Đặt một hình ảnh mặc định hoặc thực hiện hành động thích hợp khi 'qt.getHinh()' là null
                imageAvatar1.setIcon(new ImageIcon(getClass().getResource("/mnm/images/logoproject2.png")));
            }
        } else {
            // Xử lý trường hợp 'qt' là null (ID không tồn tại)
            // Ví dụ: Hiển thị một thông báo hoặc thực hiện hành động thích hợp
            System.out.println("Không tìm thấy ID: " + id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background2 = new com.admin.swing.Background();
        imageAvatar1 = new com.admin.swing.ImageAvatar();
        btnPre = new com.login.swing.Button();
        btnSave = new com.login.swing.Button();
        btnEdit = new com.login.swing.Button();
        txtSdt = new com.login.swing.TextField();
        txtEmail = new com.login.swing.TextField();
        txtName = new com.login.swing.TextField();
        txtID = new com.login.swing.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        background2.setBackground(new java.awt.Color(255, 255, 255));

        btnPre.setBackground(new java.awt.Color(157, 153, 255));
        btnPre.setForeground(new java.awt.Color(255, 255, 255));
        btnPre.setText("Quay lại");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(157, 153, 255));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(157, 153, 255));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSdt.setEditable(false);
        txtSdt.setBackground(new java.awt.Color(255, 255, 255));
        txtSdt.setLabelText("Số điện thoại");

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setLabelText("Email");

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setLabelText("Tên");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setLabelText("ID");
        txtID.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("#9Slide03 IcielSamsung Sharp Bo", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(157, 153, 255));
        jLabel1.setText("THÔNG TIN TÀI KHOẢN");

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnSave.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        txtID.setFocusable(false);
        txtEmail.setEditable(true);
        txtEmail.setFocusable(true);
        txtName.setEditable(true);
        txtSdt.setEditable(true);
        btnSave.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        // Lấy thông tin từ các trường nhập liệu
        String id = txtID.getText();// lấy id từ đâu đó, có thể là từ txtId hoặc một thành phần khác của giao diện
        // Tạo một đối tượng NhanVienQuanTri mới từ thông tin đã nhập
        NhanVienQuanTri qt = new NhanVienQuanTri();
        qt.setId(id);
        qt.setName(txtName.getText());
        qt.setEmail(txtEmail.getText());
        qt.setSdt(txtSdt.getText());

        // Gọi phương thức updateQT để cập nhật thông tin trong cơ sở dữ liệu
        int result = nvDAO.updateQT(qt);

        // Kiểm tra kết quả và thông báo cho người dùng
        if (result == 1) {
            DialogHelper.alert(this, "Cập nhật thành công");
        } else {
            DialogHelper.alert(this, "Cập nhật thất bại");
        }
        txtEmail.setEditable(false);
        txtName.setEditable(false);
        txtSdt.setEditable(false);
        btnSave.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnPreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.admin.swing.Background background2;
    private com.login.swing.Button btnEdit;
    private com.login.swing.Button btnPre;
    private com.login.swing.Button btnSave;
    private com.admin.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private com.login.swing.TextField txtEmail;
    private com.login.swing.TextField txtID;
    private com.login.swing.TextField txtName;
    private com.login.swing.TextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
