/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.admin.component;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import mnm.model.CuaHang;

/**
 *
 * @author Duc Tien
 */
public class CuaHangCard extends javax.swing.JPanel {

    public CuaHang getData() {
        return data;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    private boolean selected;

    /**
     * Creates new form CuaHang
     */
    public CuaHangCard() {
        initComponents();
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    public void addEvent(MouseAdapter event) {
        this.addMouseListener(event);
    }

    private CuaHang data;

    public void setData(CuaHang data) {
        this.data = data;
        // Lấy đường dẫn thư mục dự án
        String projectDirectory = System.getProperty("user.dir");

        // Tạo đường dẫn tương đối đến thư mục "src/mnm/images"
        String imagePath = "src/mnm/images/" + data.getHinh();

        // Tạo đường dẫn đầy đủ đến hình ảnh
        String fullPath = Paths.get(projectDirectory, imagePath).toString();
        pic.setIcon(new ImageIcon(fullPath));
        lblID.setText(data.getMaCH());
        lblName.setText(data.getTenCH());
    }

    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Vẽ hình tròn với màu nền
        g2.setColor(new Color(249, 249, 249));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);

        // Nếu được chọn, thì vẽ đường viền
        if (selected) {
            g2.setColor(new Color(94, 156, 255));
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
        }

        // Thêm đường viền (boder) với màu và kích thước mong muốn
        g2.setColor(Color.BLACK); // Thay đổi màu sắc của đường viền nếu cần
        g2.setStroke(new BasicStroke(2)); // Thay đổi kích thước của đường viền nếu cần
        g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

        g2.dispose();
        super.paint(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new com.admin.swing.ImageSP();
        lblName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 249, 249));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mnm/images/8.jpg"))); // NOI18N

        lblName.setBackground(new java.awt.Color(249, 249, 249));
        lblName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(127, 127, 127));
        lblName.setText("TenCH");

        lblID.setBackground(new java.awt.Color(249, 249, 249));
        lblID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(127, 127, 127));
        lblID.setText("MaCH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblID))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private com.admin.swing.ImageSP pic;
    // End of variables declaration//GEN-END:variables
}
